//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EITParcelDelivery.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class EITDBEntities : DbContext
    {
        public EITDBEntities()
            : base("name=EITDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cities> Cities { get; set; }
        public virtual DbSet<Edges> Edges { get; set; }
        public virtual DbSet<Parcel> Parcel { get; set; }
        public virtual DbSet<ParcelStatus> ParcelStatus { get; set; }
        public virtual DbSet<ParcelTypes> ParcelTypes { get; set; }
        public virtual DbSet<PathComponents> PathComponents { get; set; }
        public virtual DbSet<Roles> Roles { get; set; }
        public virtual DbSet<ServiceAccounts> ServiceAccounts { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<WeightPrices> WeightPrices { get; set; }
    }
}
