//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EITParcelDelivery.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parcel
    {
        public int Id { get; set; }
        public int Type { get; set; }
        public int Price { get; set; }
        public int Weight { get; set; }
        public System.DateTime ETA { get; set; }
        public int Start { get; set; }
        public int Status { get; set; }
    
        public virtual PathComponents PathComponents { get; set; }
        public virtual ParcelStatus ParcelStatus { get; set; }
        public virtual ParcelTypes ParcelTypes { get; set; }
    }
}
